import re
from datetime import datetime
from io import BytesIO

from fpdf import FPDF

MARGIN = 18
PAGE_W = 210
CONTENT_W = PAGE_W - 2 * MARGIN  # 174 — used everywhere consistently


# =========================================================
# HELPERS
# =========================================================

def _strip_markdown(text: str) -> str:
    text = re.sub(r"^#+\s*", "", text, flags=re.MULTILINE)
    text = re.sub(r"\*\*([^*]+)\*\*", r"\1", text)
    text = re.sub(r"\*([^*]+)\*", r"\1", text)
    return text.replace("\r\n", "\n").strip()


def _safe(text: str) -> str:
    """Encode to latin-1 safely, replacing unsupported characters."""
    return text.encode("latin-1", errors="replace").decode("latin-1")


def _write_paragraph(
    pdf: FPDF,
    text: str,
    bold: bool = False,
    color: tuple = (30, 41, 59),
    size: int = 10,
    line_height: int = 6,
) -> None:
    """Write a paragraph, always resetting X to MARGIN before multi_cell."""
    if not text.strip():
        return
    pdf.set_text_color(*color)
    pdf.set_font("Helvetica", "B" if bold else "", size)
    pdf.set_x(MARGIN)                      # FIX: was missing in body calls
    pdf.multi_cell(CONTENT_W, line_height, _safe(text))


def _draw_header_bar(pdf: FPDF, height: int = 30) -> None:
    """Dark navy header bar across the full page width."""
    pdf.set_fill_color(15, 23, 42)
    pdf.rect(0, 0, PAGE_W, height, style="F")


def _add_footer(pdf: FPDF) -> None:
    """Disclaimer footer at the bottom of the content area."""
    pdf.ln(6)
    _write_paragraph(
        pdf,
        (
            "Disclaimer: AI-generated draft for review only. "
            "Verify eligibility, deadlines, and funding details "
            "on official websites before submission."
        ),
        color=(130, 130, 130),
        size=8,
        line_height=5,
    )


def _meta_line(pdf: FPDF, domain: str, location: str, budget: str) -> None:
    """Render the focus-area / location / budget meta line."""
    parts = [f"Focus Area: {domain}"]
    if location:
        parts.append(f"Location: {location}")
    if budget:
        parts.append(f"Budget: {budget}")
    _write_paragraph(pdf, "  |  ".join(parts), size=9, color=(80, 80, 80))


# =========================================================
# PROPOSAL PDF
# =========================================================

def build_proposal_pdf(run_data: dict) -> bytes:
    proposal = _strip_markdown(run_data.get("proposal") or "No content generated.")
    org      = run_data.get("org_name") or "Organization"
    domain   = run_data.get("domain")   or "Project"
    location = run_data.get("location") or ""
    budget   = run_data.get("budget")   or ""

    pdf = FPDF()
    pdf.set_margins(MARGIN, MARGIN, MARGIN)
    pdf.set_auto_page_break(auto=True, margin=MARGIN)
    pdf.add_page()

    # ── HEADER ────────────────────────────────────────────
    _draw_header_bar(pdf, height=30)

    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 15)
    pdf.set_xy(MARGIN, 8)
    pdf.cell(CONTENT_W, 8, _safe("Grant Proposal — Concept Note"))

    pdf.set_font("Helvetica", "", 8)
    pdf.set_xy(MARGIN, 19)
    pdf.cell(
        CONTENT_W, 5,
        _safe(f"Generated by GrantAI  •  {datetime.now().strftime('%d %B %Y')}"),
    )

    # ── ORG NAME ──────────────────────────────────────────
    pdf.set_y(38)
    pdf.set_x(MARGIN)                      # FIX: explicit X reset after header
    pdf.set_text_color(20, 20, 20)
    pdf.set_font("Helvetica", "B", 14)
    pdf.multi_cell(CONTENT_W, 8, _safe(org))   # FIX: was cell() with no ln()
    pdf.ln(3)

    # ── META LINE ─────────────────────────────────────────
    _meta_line(pdf, domain, location, budget)
    pdf.ln(6)

    # ── HORIZONTAL RULE ───────────────────────────────────
    pdf.set_draw_color(200, 210, 230)
    pdf.line(MARGIN, pdf.get_y(), PAGE_W - MARGIN, pdf.get_y())
    pdf.ln(5)

    # ── BODY SECTIONS ─────────────────────────────────────
    section_titles = (
        "PROJECT TITLE",
        "EXECUTIVE SUMMARY",
        "PROBLEM",
        "PROBLEM & NEED",
        "APPROACH",
        "APPROACH & ACTIVITIES",
        "EXPECTED IMPACT",
        "BUDGET",
        "BUDGET SUMMARY",
        "CONCLUSION",
    )

    for block in re.split(r"\n\s*\n", proposal):
        block = block.strip()
        if not block:
            continue

        lines = [ln.strip() for ln in block.split("\n") if ln.strip()]
        if not lines:
            continue

        heading    = lines[0].upper()
        is_heading = any(heading.startswith(t) for t in section_titles)

        if is_heading:
            pdf.ln(4)
            _write_paragraph(
                pdf, lines[0],
                bold=True, color=(30, 64, 175), size=11, line_height=7,
            )
            body = " ".join(lines[1:])
        else:
            body = " ".join(lines)

        if body:
            _write_paragraph(pdf, body, size=10, line_height=6)

        pdf.ln(2)

    # ── FOOTER ────────────────────────────────────────────
    _add_footer(pdf)

    out = BytesIO()
    pdf.output(out)
    return out.getvalue()


# =========================================================
# GRANTS PDF
# =========================================================

def build_grants_pdf(run_data: dict) -> bytes:
    grants   = run_data.get("grants", [])
    org      = run_data.get("org_name") or "Organization"
    domain   = run_data.get("domain")   or "Project"
    location = run_data.get("location") or ""
    budget   = run_data.get("budget")   or ""

    pdf = FPDF()
    pdf.set_margins(MARGIN, MARGIN, MARGIN)
    pdf.set_auto_page_break(auto=True, margin=MARGIN)
    pdf.add_page()

    # ── HEADER ────────────────────────────────────────────
    _draw_header_bar(pdf, height=32)

    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_xy(MARGIN, 8)
    pdf.cell(CONTENT_W, 8, _safe("Grant Opportunity Report"))

    pdf.set_font("Helvetica", "", 8)
    pdf.set_xy(MARGIN, 20)
    pdf.cell(
        CONTENT_W, 5,
        _safe(f"Generated by GrantAI  •  {datetime.now().strftime('%d %B %Y')}"),
    )

    # ── ORG NAME ──────────────────────────────────────────
    pdf.set_y(40)
    pdf.set_x(MARGIN)                       # FIX: explicit X reset
    pdf.set_text_color(20, 20, 20)
    pdf.set_font("Helvetica", "B", 14)
    pdf.multi_cell(CONTENT_W, 8, _safe(org))  # FIX: was cell() with no ln()
    pdf.ln(3)

    # ── META LINE ─────────────────────────────────────────
    _meta_line(pdf, domain, location, budget)
    pdf.ln(6)

    # ── HORIZONTAL RULE ───────────────────────────────────
    pdf.set_draw_color(200, 210, 230)
    pdf.line(MARGIN, pdf.get_y(), PAGE_W - MARGIN, pdf.get_y())
    pdf.ln(5)

    # ── MATCH COUNT ───────────────────────────────────────
    pdf.set_x(MARGIN)
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(30, 64, 175)
    pdf.cell(CONTENT_W, 6, _safe(f"{len(grants)} matching opportunities found"))
    pdf.ln(10)

    # ── EMPTY STATE ───────────────────────────────────────
    if not grants:
        _write_paragraph(
            pdf, "No grants found matching your search.",
            color=(180, 50, 50),
        )
        _add_footer(pdf)
        out = BytesIO()
        pdf.output(out)
        return out.getvalue()

    # ── GRANT CARDS ───────────────────────────────────────
    for idx, grant in enumerate(grants[:15], 1):
        # Guard against non-numeric score values
        try:
            score = int(float(grant.get("score", 0)))
        except (TypeError, ValueError):
            score = 0

        title    = grant.get("name", "Unnamed Grant")
        desc     = (grant.get("description") or "").strip()
        amount   = grant.get("amount",   "See website")
        deadline = grant.get("deadline", "Verify online")
        url      = grant.get("url", "")
        label    = grant.get("match_label", "Relevant Match")

        # DIVIDER
        pdf.set_draw_color(220, 220, 220)
        pdf.set_x(MARGIN)
        pdf.line(MARGIN, pdf.get_y(), PAGE_W - MARGIN, pdf.get_y())
        pdf.ln(5)

        # TITLE
        pdf.set_x(MARGIN)
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(20, 20, 20)
        pdf.multi_cell(CONTENT_W, 7, _safe(f"{idx}. {title}"))
        pdf.ln(1)

        # RELEVANCE BADGE
        pdf.set_x(MARGIN)
        pdf.set_font("Helvetica", "B", 9)
        if score >= 75:
            pdf.set_text_color(0, 130, 70)
        elif score >= 50:
            pdf.set_text_color(180, 120, 0)
        else:
            pdf.set_text_color(180, 50, 50)
        pdf.cell(CONTENT_W, 5, _safe(f"Relevance: {score}%  |  {label}"))
        pdf.ln(6)

        # META (amount + deadline)
        pdf.set_x(MARGIN)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(90, 90, 90)
        pdf.multi_cell(CONTENT_W, 5, _safe(f"Funding Amount: {amount}"))

        pdf.set_x(MARGIN)                   # FIX: reset X after multi_cell
        pdf.multi_cell(CONTENT_W, 5, _safe(f"Deadline: {deadline}"))
        pdf.ln(2)

        # DESCRIPTION
        if desc:
            short_desc = desc[:220] + ("..." if len(desc) > 220 else "")
            pdf.set_x(MARGIN)
            pdf.set_text_color(50, 50, 50)
            pdf.set_font("Helvetica", "", 10)
            pdf.multi_cell(CONTENT_W, 6, _safe(short_desc))
            pdf.ln(2)

        # URL
        if url:
            short_url = url[:100] + ("..." if len(url) > 100 else "")
            pdf.set_x(MARGIN)
            pdf.set_text_color(30, 100, 180)
            pdf.set_font("Helvetica", "I", 8)
            pdf.multi_cell(CONTENT_W, 4, _safe(short_url))

        pdf.ln(7)

    # ── FOOTER ────────────────────────────────────────────
    _add_footer(pdf)

    out = BytesIO()
    pdf.output(out)
    return out.getvalue()